### ISSUE TITLE
Ensure number of rows to iterate is an integer

### ISSUE THREAD

**Issue by cdeck3r** [disloops/psadify#2]
I came across the following situation: When PSAdify is started and there has been no attackers logged to far, the python script fails in L305, because the referenced slice `top_ports[:rows/2]` does not use an integer, if the array is empty. One could think so, because `len(top_ports)` is `0` and `0/2` is `0` again. However, it does not work like that. 

There are actually two occurances of the `rows/2` expression:
https://github.com/disloops/psadify/blob/6bca0c5196a6cb4330d4257a87a47e82092bb25b/psadify.py#L305
https://github.com/disloops/psadify/blob/6bca0c5196a6cb4330d4257a87a47e82092bb25b/psadify.py#L322

A simple patch would be to replace `rows/2` by `rows//2`. The latter floors the result to the next lower integer. 

Thank you for the cool tool. 👍

**Comment by disloops** [comment]
100% correct! Thanks very much, I have updated the PSADify script.

I am glad to see that people are using this. Please let me know if you find any other issues.

Best - @disloops
